Homework4+
Li2nga/JavaCourse pull request #6
Opened 2024-06-02 13:39 UTC by NikDenAlb

2024-06-02 19:22 UTC, Li2nga requested changes

2024-06-02 19:22 UTC, Li2nga commented on src/Homework4Star/Main.java
> +                : "Если возраст человека равен " + age + ", то он совершеннолетний.");
Избежать дублирования

2024-06-02 19:22 UTC, Li2nga commented on src/Homework4Star/Main.java
> +                : "На улице " + outsideAirTemperature + " градусов -  можно идти без шапки");
тоже

2024-06-02 19:22 UTC, Li2nga commented on src/Homework4Star/Main.java
> +                : "Если скорость " + carSpeed + " км/ч, то  придется заплатить штраф");
тоже

2024-06-02 19:22 UTC, Li2nga commented on src/Homework4Star/Main.java
> +        System.out.println((age < 2) ? ", то ему нужно спать" :
вот как надо

2024-06-02 19:27 UTC, NikDenAlb commented on src/Homework4Star/Main.java
> +                : "Если возраст человека равен " + age + ", то он совершеннолетний.");
Избежать дублирования

2024-06-02 19:27 UTC, NikDenAlb commented on src/Homework4Star/Main.java
> +                : "На улице " + outsideAirTemperature + " градусов -  можно идти без шапки");
тоже

2024-06-02 19:27 UTC, NikDenAlb commented on src/Homework4Star/Main.java
> +                : "Если скорость " + carSpeed + " км/ч, то  придется заплатить штраф");
тоже

2024-06-02 19:27 UTC, NikDenAlb commented on src/Homework4Star/Main.java
> +        System.out.println((age < 2) ? ", то ему нужно спать" :
вот как надо

2024-06-03 12:56 UTC, NikDenAlb commented
Проводи. Используй силу

2024-06-03 12:57 UTC, Li2nga approved these changes

2024-06-03 12:58 UTC, merged